### ISSUE TITLE
Update to Stella 4.6

### ISSUE THREAD

**Issue by RobLoach** [libretro/stella-libretro#14]
Created a new `update` branch at https://github.com/RobLoach/stella-libretro/tree/update . It's not compiling, as I believe SDL2 headers are missing. Any assistance on it would be much appreciated.

**Comment by orbea** [comment]
Related issue. https://github.com/libretro/stella-libretro/issues/40

**Comment by RobLoach** [comment]
Thanks! Let's move this over there.
