### ISSUE TITLE
Unable to scan Atari 2600 romset

### ISSUE THREAD

**Issue by lollo78** [libretro/stella-libretro#26]
Hi, I tried with two different romset (.bin): the games works, but I have to load them manually if I want to play. 
When I launch the scanning in Retroarch, after the procedure nothing appears in the GUI.
If the issue is the romset used (different CRC from the db file), could you advice me a good romset?
I saw that No-Intro doesn't have Atari 2600 roms.
Thx

**Comment by lollo78** [comment]
I proposed a solution here:
https://github.com/libretro/libretro-database/pull/132

**Comment by RobLoach** [comment]
Merged. Could close this issue.
