### ISSUE TITLE
[Wii U] Corrupted graphics

### ISSUE THREAD

**Issue by cucholix** [libretro/stella-libretro#41]
The Wii U port has corrupted graphics in game. 
This is how Battlezone looks:
![img_20180108_231352958_hdr](https://user-images.githubusercontent.com/16081693/34702735-2227f1b8-f4ce-11e7-97d7-cb0d44592e70.jpg)

By reference the game normally:
https://vignette.wikia.nocookie.net/thegameroom/images/5/5a/Battlezone_Atari_2600_Gameplay.png

The last working build (that I own) is from 29-12-17.

**Comment by Sin2FX** [comment]
Same problem recently started on PS2. Looks like a long lived bug
